### PR TITLE
feat(http): adding headers support

### PR DESCRIPTION
**Pull request by isabr85**
Adding headers support

### CODE REVIEW

**Comment by snakefoot** [comment]
Maybe consider implementing Headers like this:

```c#
        [ArrayParameter(typeof(MethodCallParameter), "header")]
        public IList<MethodCallParameter> Headers { get; } = new List<MethodCallParameter>();
```

And render like this:

```c#
            if (Headers?.Count > 0)
            {
                for (int i = 0; i < Headers.Count; i++)
                {
                    string headerValue = RenderLogEvent(Headers[i].Layout, logEvent.LogEvent);
                    if (headerValue == null)
                        continue;

                    _httpClient.DefaultRequestHeaders.Add(Headers[i].Name, headerValue);
                }
            }
```

Then it would be possible to use NLog-Layout-logic to retrieve Header-values (Ex. from app.config / appsettings.json).

**Comment by isabr85** [comment]
This solution isn't working for me, I don't know why.
I implemented your proposal in my local environment, the I configured my NLog.config to be like this:

```
<target     type="HTTP"
                  name="ws"
                  Method='POST'
                  URL="https://log-api.eu.newrelic.com/log/v1"
                  ContentType='application/json'
                  Accept='application/json'
                  header='${configsetting:name=headerName}'
```
And my appsettings.json file I have the expected header value:
```
{
  "headerName": "headerValue"
}
```

But Headers parameter within the code remain empty

**Comment by snakefoot** [comment]
Was thinking like this:

```xml
<target     type="HTTP"
                  name="ws"
                  Method='POST'
                  URL="https://log-api.eu.newrelic.com/log/v1"
                  ContentType='application/json'
                  Accept='application/json'>
    <header name="X-License-Key" layout="${environment:LICENSE_KEY}"/>
</target>
```

**Comment by isabr85** [comment]
PR updated.

**Review by snakefoot — APPROVED** [review]

**Comment by snakefoot** [comment]
@DarekDan Possible to have this feature merged ?

**Comment by snakefoot** [comment]
@DarekDan Created #24 since NHttpHeader is missing NLog Layout-support.

**Comment by DarekDan** [comment]
I will review next week. There are merge conflicts.

**Comment by snakefoot** [comment]
> @DarekDan I will review next week. There are merge conflicts.

This pull-request has been super-seeded by f18b82484fede3f632e1f36dde091773dc84993f (And should be closed)

**Comment by DarekDan** [comment]
This feature already exists. 

```
<!-- optional additional HTTP Headers -->
    <header name='key' value='value'/>
    <!-- additional headers -->
```

**Pull request closed without merging**
