### PR TITLE
OptimizeBufferReuse and stop allocating StrongBox-objects

### PR DESCRIPTION
**Pull request by snakefoot**
Also fixed flushing to be non-blocking, as expected by NLog. Curious why `FlushBeforeShutdown`-option exists, since NLog automatically performs flush on "shutdown".

### CODE REVIEW

**Comment by DarekDan** [comment]
I am concerned with dropping StrongBox<> from the code. It is faster to re-enqueue a reference than to copy a bunch of bytes from one memory block to another, I would hope. The swap of HttpClient is intriguing but would require a new instance to be created on every call. I'm open to the PR, just want to ensure that no additional stress would be put on the system. When testing with 1M POSTs over 8s the memory is already a sensitive area. Additionally, are people out there using HTTP GET to submit log entries? Quite an odd scenario.

**Comment by snakefoot** [comment]
> I am concerned with dropping StrongBox<> from the code. It is faster to re-enqueue a reference than to copy a bunch of bytes from one memory block to another,

Reference-to-byte-array has the same size as reference-to-strongbox-object. The only difference is not allocating strongbox-object. The StrongBox-wrapper is intended for value-types (structs), allowing multiple references to the same mutable struct. Not usually for wrapping other reference-types.

> The swap of HttpClient is intriguing but would require a new instance to be created on every call. 

There is no swap of HttpClient in this PR. Just removed class-variables (`_handler`) that was not referenced anywhere besides in the local-function.

> Additionally, are people out there using HTTP GET to submit log entries?

Will update the PR to remove this dictionary-lookup completely. String-HashCode + Dictionary-Lookup for every request generates an unnecessary overhead (Was just trying to remove the ToLower-string-allocation, but the whole thing should be removed)

**Comment by DarekDan** [comment]
You might be onto something here ... Initially it was reported to me that with the StrongBox wrapper, a few were able to observe a memory stress, but now I can't duplicate such observation.

**Comment by snakefoot** [comment]
Removed AvailableHttpMethods-Dictionary-Lookups and replaced with simple enum-switch

**Pull request merged**
